# Generated by Django 5.0.6 on 2025-01-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_remove_mission_complete_mission_status_and_more'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='complete',
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('complete', 'Complete')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='missions.mission'),
        ),
    ]
